dataset:
  image_base_dir: "/srv/datasets3/HoliCity/images"
  vpts_base_dir: "/srv/datasets3/HoliCity/vanishing_points/"
  dataset_dir: "/srv/datasets3/HoliCity/dataset_w_vpts/"

training:
  threshold:
    distance_from_vanishing_point: 10
  additional_loss_weight: 0.01

