dataset:
  image_base_dir: "/srv/datasets3/HoliCity/images"
  vpts_base_dir: "/srv/datasets3/HoliCity/vpts-w-edges/"
  dataset_dir: "/srv/datasets3/HoliCity/dataset_w_vpts_edges/"

training:
  threshold:
    distance_from_vanishing_point: 10
  additional_loss_weight: 10 # tog:0.01

